Thu May 27 17:24:19 SGT 2021 Thread[Shutdown,5,Apache SIS] Cleanup action starting
java.sql.SQLException: Database 'classpath:SIS_DATA/Databases/SpatialMetadata' not found.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.BasicEmbeddedDataSource40.getConnection(Unknown Source)
	at org.apache.derby.jdbc.BasicEmbeddedDataSource40.getConnection(Unknown Source)
	at org.apache.sis.internal.metadata.sql.Initializer.shutdown(Initializer.java:569)
	at org.apache.sis.internal.metadata.sql.Initializer.lambda$getDataSource$1(Initializer.java:392)
	at org.apache.sis.internal.system.Shutdown.stop(Shutdown.java:183)
	at org.apache.sis.internal.system.Shutdown.run(Shutdown.java:66)
Caused by: ERROR XJ004: Database 'classpath:SIS_DATA/Databases/SpatialMetadata' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 18 more
============= begin nested exception, level (1) ===========
ERROR XJ004: Database 'classpath:SIS_DATA/Databases/SpatialMetadata' not found.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleDBNotFound(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.BasicEmbeddedDataSource40.getConnection(Unknown Source)
	at org.apache.derby.jdbc.BasicEmbeddedDataSource40.getConnection(Unknown Source)
	at org.apache.sis.internal.metadata.sql.Initializer.shutdown(Initializer.java:569)
	at org.apache.sis.internal.metadata.sql.Initializer.lambda$getDataSource$1(Initializer.java:392)
	at org.apache.sis.internal.system.Shutdown.stop(Shutdown.java:183)
	at org.apache.sis.internal.system.Shutdown.run(Shutdown.java:66)
============= end nested exception, level (1) ===========
Cleanup action completed
